version: '1'
services:
  data_extraction_service:
    build: 
      context: ../
      dockerfile: data_extraction/docker/Dockerfile
    ports:
      - "8888:8888"
  data_extraction_paddle_service:
    build: 
      context: ../
      dockerfile: data_extraction/docker/PaddleDockerfile
    ports:
      - "8888:8888"